export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const ADD_PROJECT = 'ADD_PROJECT';
export const ADD_DEVELOPER_LIST='ADD_DEVELOPER_LIST';
export const ADD_DEVELOPER='ADD_DEVELOPER';
export const ADD_TECHNOLOGY='ADD_TECHNOLOGY';
export const ADD_PROJECT_LIST='ADD_PROJECT_LIST';
export const ADD_ALL_DEVELOPER='ADD_ALL_DEVELOPER';
export const ADD_ASSIGNED_PROJECT ='ADD_ASSIGNED_PROJECT'
export const ADD_TASK ='ADD_TASK'

